### PR TITLE
Ensure that `ghc-events show` fails with an error on malformed events

### LINKED ISSUE #85: ghc-events show should exit with an error by default if it fails to consume the complete eventlog.
This would make debugging issues with incomplete/partial/corrupted eventlogs easier.

### PR DESCRIPTION
**Pull request by bgamari**
Previous `ghc-events show` would fail to report malformed events. Here we fix this by splitting up `readEvents` to offer:
```haskell
readEvents' :: Header -> BL.ByteString -> [Either String Event]
```
Which gives the user access to event deserialisation errors.

Fixes #85.

### CODE REVIEW

**Comment by AndreasPK** [comment]
LGTM for what it's worth

File: src/GHC/RTS/Events/Incremental.hs [hunk 1]
```diff
@@ -154,6 +164,20 @@ readEventLog bytes = do
...
+--
+-- This will raise an error if a malformed event is encountered during decoding.
+readEventLogOrFail :: BL.ByteString -> Either String EventLog
+readEventLogOrFail bytes = do
+    (header, bs') <- readHeader bytes
+    let events = zipWith idOrThrowErr [1..] (readEvents' header bs')
+    return $ EventLog header (Data events)
+  where
+    idOrThrowErr :: Int -> Either String Event -> Event
+    idOrThrowErr i (Left err) = error $ "readLogOrDie: error deserialising event " ++ show i ++ ": " ++ err
```
Comment (maoe) [inline src/GHC/RTS/Events/Incremental.hs:178]: I suspect the error message here is meant to be
```suggestion
    idOrThrowErr i (Left err) = error $ "readEventLogOrFail: error deserialising event " ++ show i ++ ": " ++ err
```

**Review by maoe — COMMENTED** [review]
LGTM. Found possibly a typo in an error message.

**Comment by bgamari** [comment]
I have merged your fix and squashed.

**Comment by maoe** [comment]
Thanks!

**Comment by maoe** [comment]
Released https://hackage.haskell.org/package/ghc-events-0.18.0
